knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/bin/wkhtmltopdf.sh'
        options:    []
    image:
        enabled:    false
        binary:     ~
        options:    []
