knp_snappy:
    pdf:
        enabled:    true
#        binary:     '%kernel.project_dir%/bin/wkhtmltopdf.sh'
        binary:     '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:    []
    image:
        enabled:    false
        binary:     ~
        options:    []
