twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form.html.twig']
    globals:
        IP_SEDONA: 213.182.58.194
        contact_email: '%env(REPLY_TO_EMAIL)%'
