include:
  #####
  ## Global init
  #####
  - project: php/php-ci-templates
    ref: master
    file: global_init.yml

stages:
  - quality
  - compileJS
  - build
  - publish
  - deploy

cache:
  key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME"
  untracked: false
  paths:
    - build/
    - public/build/
    - gl-code-quality-report.json

quality:sonar:
  stage: quality
  image: "${SONAR_SCANNER_DOCKER_IMAGE}:${SONAR_SCANNER_DOCKER_IMAGE_VERSION}"
  script:
    - cd $WORKSPACE_DIR
    - make -B sonar-project.properties
    - sonar-scanner -Dsonar.login=${SONAR_TOKEN}


compileJS:
  stage: compileJS
  image: node:10-alpine
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push
    paths:
      - public/build/
  artifacts:
    untracked: false
    expire_in: 90 mins
  script:
    - npm install
    - yarn encore production

#build:package:
#  stage: build
#  needs: ["compileJS"]
#  image: registry.sedona.fr/images/php:7
#  cache:
#    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
#    untracked: true
#    paths:
#      - build/
#      - public/build/
#  artifacts:
#    untracked: false
#    expire_in: 90 mins
#  script:
#    - make dotenv-make default clean
#build:image:
#  stage: build
#  needs: ["compileJS"]
#  only:
#    - master
#    - tags
#  image: docker:latest
#  cache:
#    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
#    untracked: true
#    policy: pull
#    paths:
#      - public/build/
#  before_script:
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.sedona.fr
#    - apk update
#    - apk add make
#  script:
#    - APP_IMAGE_TAG=$(make show-var-DOCKER_TAG)
#    - DB_IMAGE_TAG=${APP_IMAGE_TAG/\/site/\/db}
#    - make image
#    - docker build -t $DB_IMAGE_TAG -f .deploy/db.Dockerfile .deploy
#
#publish:package:
#  stage: publish
#  needs: ["compileJS","build:package"]
#  only:
#    - master
#    - tags
#  image: "registry.sedona.fr/images/maven:latest-gitlab-ci"
#  cache:
#    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
#    untracked: true
#    policy: pull
#    paths:
#      - build/
#  script:
#    - GROUP_ID=$(make show-var-GROUP_ID)
#    - ARTIFACT_ID=$(make show-var-ARTIFACT_ID)
#    - VERSION=$(make show-var-VERSION)
#    - FILE_NAME=$(make show-var-PACKAGE_NAME)
#    - NEXUS_ID=$([ -z "${CI_COMMIT_TAG}" ] && echo "sedona-php-snapshot" || echo "sedona-php-release")
#    - NEXUS_URL=$([ -z "${CI_COMMIT_TAG}" ] && echo "php-snapshot" || echo "php-release")
#    - mvn deploy:deploy-file -X -Durl=https://repo.cicd.sedona.fr/artifactory/${NEXUS_URL} -DrepositoryId=${NEXUS_ID} -Dfile=build/${FILE_NAME} -DgroupId=${GROUP_ID} -DartifactId=${ARTIFACT_ID} -Dversion=${VERSION} -Dpackaging=tgz
#
#publish:image:
#  stage: publish
#  needs: ["compileJS", "build:image"]
#  only:
#    - master
#    - tags
#  before_script:
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.sedona.fr
#    - apk update
#    - apk add make
#  script:
#    - APP_IMAGE_TAG=$(make show-var-DOCKER_TAG)
#    - DB_IMAGE_TAG=${APP_IMAGE_TAG/\/site/\/db}
#    - docker push $APP_IMAGE_TAG
#    - docker push $DB_IMAGE_TAG
#    - docker rmi -f $APP_IMAGE_TAG $DB_IMAGE_TAG
