include:
  #####
  ## Global init
  #####
  - project: php/php-ci-templates
    ref: master
    file: global_init.yml

stages:
  - quality
  - compileJS
  - test
  - check-release
  - build
  - publish

cache:
  key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME"
  untracked: false
  paths:
    - build/
    - public/build/
    - gl-code-quality-report.json
    - vendor/

variables:
  PHP_IMAGE: "registry.sedona.fr/images/php:7.4"
  POSTGRES_DB: "catalogue"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "Welcome09"

quality:sonar:
  extends: .quality:sonar

compileJS:
  stage: compileJS
  image: node:10-alpine
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push
    paths:
      - public/build/
  artifacts:
    untracked: false
    expire_in: 90 mins
    paths:
      - public/build/
  script:
    - npm install
    - yarn encore production

test:php:
  extends: .test:php
  needs: ["compileJS"]
  script:
    - wait-for-it db:5432 -s -t 30 -- echo "Postgres ready"
    - make tests

check-release:
  extends: .check-release

build:image:
  extends: .build:image-db-only
  rules:
  - if: $CI_COMMIT_TAG

publish:image:
  extends: .publish:image-db-only
  needs: ["build:image"]
  rules:
  - if: $CI_COMMIT_TAG
