include:
  #####
  ## Global init
  #####
  - project: php/php-ci-templates
    ref: master
    file: global_init.yml

stages:
  - quality
  - compileJS
cache:
  key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME"
  untracked: false
  paths:
    - build/
    - public/build/
    - gl-code-quality-report.json

quality:sonar:
  stage: quality
  image: "${SONAR_SCANNER_DOCKER_IMAGE}:${SONAR_SCANNER_DOCKER_IMAGE_VERSION}"
  script:
    - cd $WORKSPACE_DIR
    - make -B sonar-project.properties
    - sonar-scanner -Dsonar.login=${SONAR_TOKEN}


compileJS:
  stage: compileJS
  image: node:10-alpine
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push
    paths:
      - public/build/
  artifacts:
    untracked: false
    expire_in: 90 mins
  script:
    - npm install
    - yarn encore production
