stages:
  - quality
  - compileJS
  - build
  - publish
  - deploy

variables:
  RANCHER_CLI_VERSION: "v0.6.10"
  RANCHER_STACK_NAME: "bpi-catalogue"
  RANCHER_STACK_URL: https://bpi-catalogue.dev.sedona.fr
  SENSIO_INSIGHT_PROJECT_ID: "d00b38e4-085a-4648-b87f-86de05d98aab"

cache:
  key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME"
  untracked: false
  paths:
    - build/
    - public/build/
    - gl-code-quality-report.json

quality:sonar:
  stage: quality
  image: "registry.sedona.fr/images/maven:latest-gitlab-ci"
  script:
    - GROUP_ID=$(make show-var-GROUP_ID)
    - ARTIFACT_ID=$(make show-var-ARTIFACT_ID)
    - CLIENT_NAME=$(make show-var-CLIENT_NAME)
    - COMPOSER_PROJECT_DESCRIPTION=$(make show-var-COMPOSER_PROJECT_DESCRIPTION)
    - sed -i -E "s/sonar.projectKey=[^)]+/sonar.projectKey=$GROUP_ID:$ARTIFACT_ID/g" sonar-project.properties
    - sed -i -E "s/sonar.projectName=[^)]+/sonar.projectName=[$CLIENT_NAME] $COMPOSER_PROJECT_DESCRIPTION /g" sonar-project.properties
    - sed -i -E "s/sonar.projectVersion=[^)]+/sonar.projectVersion=$CI_COMMIT_REF_NAME/g" sonar-project.properties
    - 'sonar-scanner'

quality:insight:
  stage: quality
  image: "registry.sedona.fr/images/php:7-fpm"
  script:
    - apt-get install -y -qq jq wget
    - export PR_ID=$(curl -s "https://git.sedona.fr/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${USER_TOKEN}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.iid")
    - echo $PR_ID
    - >
        if [[ ! -z "$PR_ID" ]] ; then
            wget https://github.com/bdemalglaive/insight/raw/master/build/insight.phar
            php insight.phar diff ${SENSIO_INSIGHT_PROJECT_ID} --user-uuid=${SENSIO_INSIGHT_USER_UUID} --api-token=${SENSIO_INSIGHT_USER_TOKEN} --format=md --reference-base=$(git rev-parse master) --reference-head=$(git rev-parse HEAD) > gl-code-quality-report.json
            export LAST_NOTES_ID=$(curl -s "https://git.sedona.fr/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${PR_ID}/notes?private_token=LkssJDBWsn4TuspWeQty&state=opened" | jq -r ".[]|select(.author.id == 106)|.id")
            [ -z "${LAST_NOTES_ID}" ] && curl -i -X POST -H 'Content-Type: application/json' -d '@gl-code-quality-report.json' "https://git.sedona.fr/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${PR_ID}/notes?private_token=${USER_TOKEN}" || curl -i -X PUT -H 'Content-Type: application/json' -d '@gl-code-quality-report.json' "https://git.sedona.fr/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${PR_ID}/notes/${LAST_NOTES_ID}?private_token=${USER_TOKEN}"
        fi
  artifacts:
    paths: [gl-code-quality-report.json]

#quality:w3c:
#  stage: quality
#  image: registry.sedona.fr/images/php:7
#  script:
#    - make dotenv-make c-install behat-w3c
#  artifacts:
#    name: "test"
#    paths:
#      - build/
#    when: on_failure
#    expire_in: 20 minutes
#    untracked: true

compileJS:
  stage: compileJS
  image: node:10-alpine
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push
    paths:
      - public/build/
  artifacts:
    untracked: false
    expire_in: 90 mins
  script:
    - npm install
    - yarn encore production

build:package:
  stage: build
  needs: ["compileJS"]
  dependencies:
    - compileJS
  image: registry.sedona.fr/images/php:7
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    paths:
      - build/
      - public/build/
  artifacts:
    untracked: false
    expire_in: 90 mins
  script:
    - make dotenv-make default clean

build:image:
  stage: build
  needs: ["compileJS"]
  dependencies:
    - compileJS
  only:
    - feature-coloriage
  image: docker:latest
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: pull
    paths:
      - public/build/
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.sedona.fr
    - apk update
    - apk add make
  script:
    - APP_IMAGE_TAG=$(make show-var-DOCKER_TAG)
    - DB_IMAGE_TAG=${APP_IMAGE_TAG/\/site/\/db}
    - make image
    - docker build -t $DB_IMAGE_TAG -f .deploy/db.Dockerfile .deploy

publish:package:
  stage: publish
  needs: ["build:package"]
  dependencies:
    - build:package
  image: "registry.sedona.fr/images/maven:latest-gitlab-ci"
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: pull
    paths:
      - build/
  script:
    - GROUP_ID=$(make show-var-GROUP_ID)
    - ARTIFACT_ID=$(make show-var-ARTIFACT_ID)
    - VERSION=$(make show-var-VERSION)
    - FILE_NAME=$(make show-var-PACKAGE_NAME)
    - NEXUS_ID=$([ -z "${CI_COMMIT_TAG}" ] && echo "sedona-php-snapshot" || echo "sedona-php-release")
    - NEXUS_URL=$([ -z "${CI_COMMIT_TAG}" ] && echo "php-snapshot" || echo "php-release")
    - mvn deploy:deploy-file -X -Durl=https://repo.cicd.sedona.fr/artifactory/${NEXUS_URL} -DrepositoryId=${NEXUS_ID} -Dfile=build/${FILE_NAME} -DgroupId=${GROUP_ID} -DartifactId=${ARTIFACT_ID} -Dversion=${VERSION} -Dpackaging=tgz

publish:image:
  stage: publish
  needs: ["build:image"]
  dependencies:
    - build:image
  only:
    - feature-coloriage
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.sedona.fr
    - apk update
    - apk add make
  script:
    - APP_IMAGE_TAG=$(make show-var-DOCKER_TAG)
    - DB_IMAGE_TAG=${APP_IMAGE_TAG/\/site/\/db}
    - docker push $APP_IMAGE_TAG
    - docker push $DB_IMAGE_TAG
    - docker rmi -f $APP_IMAGE_TAG $DB_IMAGE_TAG

deploy:rancher_dev:
  stage: deploy
  needs: ["publish:image"]
  dependencies:
    - publish:image
  only:
    - feature-coloriage
  image:
    name: "rancher/cli:$RANCHER_CLI_VERSION"
    entrypoint: ["/bin/sh", "-c"]
  when: manual
  environment:
    name: dev-rancher
    url: $RANCHER_STACK_URL
  script:
    - rancher up --stack $RANCHER_STACK_NAME -d --confirm-upgrade --force-recreate --pull --file .deploy/rancher/docker-compose.yml --rancher-file .deploy/rancher/rancher-compose.yml app
