version: '3.5'

services:

  app:
    depends_on:
      - db
      - redis
    networks:
      - default

  db:
    image: postgres:9.6
    networks:
      - default

  redis:
    image: redis:3.2
    networks:
      - default

networks:
  default: {}
