version: '3.5'

services:

  app:
    depends_on:
      - db
    networks:
      - default

  db:
    image: registry.sedona.fr/images/postgres:9.6
    networks:
      - default

networks:
  default: {}
