version: '3.5'
services:
  app:
    image: registry.sedona.fr/images/php:7-fpm
    user: '$UID:$UID'
    networks:
      - default
    environment:
      - COMPOSER_HOME=$COMPOSER_CONTAINER_HOME
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MAILER_URL
      - PROJECT_HOSTNAME
      - PROJECT_SCHEME
      - PROJECT_BASEPATH
      - PROJECT_ENVIRONMENT
      - APP_ENV
      - APP_SECRET
    volumes:
      - ./:/var/www/html/
      - .deploy/dev/app/docker-php-ext-pgsql.ini:/usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini
      - $COMPOSER_LOCAL_HOME:$COMPOSER_CONTAINER_HOME

  web:
    image: registry.sedona.fr/images/httpd:24
    networks:
      - default
      - public
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: $PROJECT_HOSTNAME"
      traefik.frontend.entryPoints: http,https
      traefik.docker.network: "$PUBLIC_NETWORK"
    volumes:
      - ./:/var/www/html/
      - .deploy/dev/web/:/usr/local/apache2/conf.d/

  db:
    image: registry.sedona.fr/images/postgres:9.6
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    ports:
      - "6379:6379"

networks:
  public:
    external: true
    name: "$PUBLIC_NETWORK"
