version: '3.5'
services:

  web:
    build:
      context: .
      dockerfile: .deploy/dev/web/Dockerfile
    networks:
      default: 
        aliases:
          - $PROJECT_HOSTNAME
      public: ~
    labels:
      traefik.enable: 1
      traefik.frontend.rule: "Host: $PROJECT_HOSTNAME"
      traefik.frontend.entryPoints: http,https
      traefik.docker.network: "$PUBLIC_NETWORK"
    volumes:
      - ./:/var/www/html/
      - ./.deploy/dev/web/:/usr/local/apache2/conf.d/

  app:
    image: registry.sedona.fr/images/php:7.4-fpm
#    user: '$UID:$UID'
    networks:
      - default
      - public
    environment:
      - COMPOSER_HOME=$COMPOSER_CONTAINER_HOME
      - PROJECT_HOSTNAME
      - PROJECT_SCHEME
      - PROJECT_BASEPATH
      - PROJECT_ENVIRONMENT
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MAILER_URL
    volumes:
      - ./:/var/www/html/
      - "$COMPOSER_LOCAL_HOME:$COMPOSER_CONTAINER_HOME"
      - ./.deploy/dev/app:/docker-entrypoint-init.d

  encore:
    image: node:10
    user: "$UID:$UID"
    environment:
      - APP_ENV
    volumes:
      - ./:/app
      - ./var/cache/npm:/.npm
      - ./.deploy/dev/encore/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    working_dir: /app
    depends_on:
      - app
    labels:
      traefik.enable: 0
    networks:
      - default

  db:
    image: postgres:9.6
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    ports:
      - "6379:6379"

networks:
  public:
    external: true
    name: "$PUBLIC_NETWORK"
