# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

home:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: "/%locale%"
    permanent: true

binary_image:
  path: "/imported_images/{type}/{content}.jpg"
  controller: 'App\Controller\Image\ImageController::binary'
  requirements:
    _method: GET
    content: ".*"


fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_logout:
  path: /{_locale}/logout
  methods: GET

# config/routes/dev/twig.yaml
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix:   /_error
