version: '2'
services:
  app:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: "bpi-catalogue.dev.sedona.fr"
        target_port: 80
  smtp:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: "mail.bpi-catalogue.dev.sedona.fr"
        target_port: 8025
  db:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
  vpn:
    scale: 1
    start_on_create: true
